apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ah-oauth-uat-api
  title: ah-oauth-uat-api 
spec:
  type: API
  lifecycle: production
  owner: micr
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "/{proxy+}"
  title: "/{proxy+}"
  description: method
  tags:
    - POST method
spec:
  type: api 
  lifecycle: production
  owner: micr
  definition: unknown
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "/"
  title: "/"
spec:
  type: api 
  lifecycle: production
  owner: micr
  consumesApis:
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:083133289548:function:ah-oauth-api-handler/invocations
  title: "function:ah-oauth-api-handler"
  description: Lambda Mapping
  tags:
    - Lambda
spec:
  type: library
  lifecycle: production
  owner: micr
  definition: unknown
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:083133289548:function:ah-oauth-api-handler/invocations
  title: function:ah-oauth-api-handler
spec:
  type: library
  lifecycle: production
  owner: micr 
---
